MakieOrg/AlgebraOfGraphics.jl

README.md, examples/README.jl, examples/makie.jl, src/context.jl, src/makie_integration.jl, src/trace.jl, src/utils.jl, test/runtests.jl
This ditches the `+` overload in favor of lists and broadcasting. Multiple lists can be combined in various ways using `[trace1 trace2] .|> [trace3, trace4]`. When continuing the pipeline the resulting object  (an array of traces) becomes the data of a new trace.
=> Combine things with lists and potentially nested objects

src/makielayout_integration.jl
I changed the way these functions work by default at some point, but in the way used here it's better to keep the grid
=> leave grid when hiding decorations

docs/src/generated/tutorial.jl, src/analysis/smooth.jl
With this PR one can pass weights to linear,
```julia
aog = data(df) * cols * style(wts=:pop2000) * linear)
```
GLM.jl has not yet implemented confidence intervals for weighted OLS.
Thus, I implemented specification of interval type `{:prediction, :confidence, nothing}` as well.  So one can do
```julia
aog = data(df) * cols * style(wts=:pop2000) * linear(interval=nothing)
```
now.
```julia
using AbstractPlotting, CairoMakie, MakieLayout, AlgebraOfGraphics
N = 150
x = rand(2N)
gx = rand(["x grp 1","x grp 2", "x grp 3"], 2N)
gy = rand(["y grp 1","y grp 2"], 2N)
wts = [fill(3, N); fill(0, N)]
df = DataFrame(x = x, y = x .+ wts .+ randn(2N), gx=gx, gy=gy, wts=wts)
cols = style(:x, :y);
grp = style(layout_x=:gx, layout_y=:gy)
scat = spec(Scatter)
pipeline1 = cols * (scat * style(color=:wts) + …
```
=> Allow weights in `linear`

Project.toml
v0.12 includes MakieLayout as submodule, but is not yet usable with CairoMakie.
In the meantime I propose to bind the version to 0.11
=> add Compat for AbstractPlotting

src/draw.jl
This fixes a bug introduced in #54: for plots without layout_{x,y} the {x,y} label is not shown.
This is fixed now:
Case 1:
Case 2:
Case 3:
Case 4:
Case 5:
=> fix axis labels of single row and single column plots

src/legend.jl
Currently, if a grouping variable is used twice, this will produce two identical legends.
```julia
using RDatasets: dataset
using AlgebraOfGraphics, AbstractPlotting, CairoMakie
mpg = dataset("ggplot2", "mpg");
cols = style(:Displ, :Hwy);
grp = style(color = :Cyl => categorical, marker=:Cyl => categorical);
scat = spec(Scatter, markersize=10px)
pipeline = cols * scat
scn = data(mpg) * grp * pipeline |> draw
```
before:
with this PR this doesn't happen any longer
probably the implementation is overkill. It seems (but I cannot prove) that the for a given grouping variable the legends are always identical. In that case a simple filtering would suffice.
=> Remove duplicated legends when grouping variable is used more than once

src/legend.jl
LLegend shows an empty row for an empty string, so we pass `nothing` for empty titles instead
=> Hide empty legend titles

src/draw.jl
This implements a feature of `ggplot2` that implements grouping without a legend entry.
Use case 1: You have a plot with many groups, but only some of them are interesting.
Use case 2: You want to plot many lines from long data, in the same color.
```julia
using DataFrames, AlgebraOfGraphics, CairoMakie, AbstractPlotting
grps = 1:15
df = mapreduce(vcat, grps) do (i_grp)
rw_i = cumsum(rand(10)) .+ i_grp
map(enumerate(rw_i)) do (t, x)
(grp=i_grp, t=t, val=x)
end
end |> DataFrame
data(df) * spec(Lines) * style(:t, :val, group=:grp) |> draw |> x -> save("/tmp/group1.png", x)
```
```julia
transform!(df, :grp => ByRow(x -> (8 <= x <= 10 ? x : "other")) => :highlight)
data(df) * spec(Lines) * style(:t, :val, group=:grp, color=:highlight) |> draw |> x -> save("/tmp/group1.png", x)
```
=> no legend-entry for `group`

src/AlgebraOfGraphics.jl, src/utils.jl
`unname` is the operation that semantically does this:
See:
https://github.com/invenia/NamedDims.jl/blob/942bb283c62dd64c0ca484bda19c1bb832f268fa/src/name_operations.jl#L45-L46
Under the hood it just calls `parent` but seem more semantic to use `unname`.
Potentially could just replace all uses of `strip_names` with `unname`
=> use NamedDims unname to remove names

Project.toml, examples/gui.jl, src/AlgebraOfGraphics.jl, src/draw.jl, src/legend.jl
AbstractPlotting renamed a bunch of things recently.
This change propagates those renames to AlgebraOfGraphics.
=> Rename types from AbstractPlotting.

docs/src/generated/penguins.jl
The penguin tutorial shows linear fits on female and male plots using
```julia
layers = linear() + mapping(col = :sex)
plt = penguin_bill * layers * mapping(color = :species)
draw(plt; axis)
```
The sex mapping is applied only to the scatter so the same fit is shown left and right. Is this intentional? This PR first shows a specific fit for each sex:
```julia
layers = linear() + mapping()
plt = penguin_bill * layers * mapping(color = :species, col = :sex)
draw(plt; axis)
```
then shows how to pool data from both sexes (i.e showing the original code).
=> clarify tutorial fit grouping

src/algebra/processing.jl, src/guides/legend.jl, test/runtests.jl
=> all data entries must be equal when merging labels

Project.toml, docs/src/generated/gallery.jl, src/helpers.jl, test/runtests.jl
Fixes #197 (for real this time). Allow `renamer(labels)` to rename a `dims` mapping while preserving the order.
=> support renaming dims selector

docs/src/generated/visual.jl
I've added some clarifications for how keyword arguments are passed (it was not obvious to me until I read the source)
I've indicated that any `@recipe` created plot function can be used with `visual`, since this was also not obvious to me until I read the source / read the response in #321 
By the way, thanks for creating this awesome package!
=> Clarify docs for `visual`

docs/src/index.md, docs/src/layers/introduction.md
Just fixed a typo in the documentation. 
Thank you very much for the development and maintenance of this great package!
=> Fix a typo in the docs

docs/gallery/gallery/applications/time_series.jl, src/AlgebraOfGraphics.jl, src/algebra/layer.jl, src/algebra/layers.jl, src/scales.jl, test/runtests.jl, test/scales.jl
=> correct width for date axis

test/facet.jl
Sets are now used in Makie when linking axes (https://github.com/JuliaPlots/Makie.jl/pull/2116/files#diff-0e352caa51e7f7cbfbdfc6e56c0ded4d3ed714cf9770d011c283cbb561eb3e49R1014) so order is not preserved anymore for linked axis. Hence, the AOG tests should not compare vectors, but sets. This fixes the failing tests.
=> ignore order in axes linking tests

.gitignore, Project.toml, docs/gallery/gallery/layout/faceting.jl, docs/src/API/functions.md, src/AlgebraOfGraphics.jl, src/algebra/layer.jl, src/algebra/layers.jl, src/draw.jl, src/paginate.jl, test/paginate.jl, test/runtests.jl
This PR adds pagination as discussed in https://github.com/JuliaPlots/AlgebraOfGraphics.jl/issues/303.
The approach is pretty much what @MichaelHatherly detailed in that post, I made some smaller changes and added tests and docs. Layer objects are split into groups depending on the maximum number of rows/columns/wrapped facets allowed and therefore `draw` returns a `Vector{FigureGrid}`. There's also a `draw(paginated, i)` method in case not all figures should live in memory at the same time, this method returns a `FigureGrid` accordingly.
=> Pagination

src/AlgebraOfGraphics.jl
`Layer` and `ProcessedLayer` are already exported. Why not `Layers`?
I need this in order to store plots in a custom struct:
```julia
struct MyType
p1::Layer
p2::Layers
end
```
=> Export Layers type

Project.toml, examples/gui.jl, src/facet.jl, test/facet.jl
Makie v0.19 was just released with this breaking change (https://github.com/MakieOrg/Makie.jl/blob/master/NEWS.md#v0190):
>Breaking The attribute textsize has been removed everywhere in favor of the attribute fontsize which had also been in use. To migrate, search and replace all uses of textsize to fontsize https://github.com/MakieOrg/Makie.jl/pull/2387.
This PR makes AoG compatible with Make v0.19, and stops supporting previous versions of Makie.
=> Support makie v0.19

docs/gallery/gallery/customization/legend.jl
Add an example to legend tweaking, demonstrating the use of `legend!`.
Related: #394.  This may be sufficient to close that?
=> doc: Example for legend!

src/guides/legendelements.jl
Hello! I recently tried to generate a plot with `ScatterLines` specifying `mapping(...; marker=:var, linestyle=:var)`, but the resulting legend didn't show the styling appropriately. I noticed that this was pointed out on #435, along with a similar issue for `VLines`, so I followed @skleinbo's recommendation and modified `src/guides/legendelements.jl` the following way:
- Changed `legend_elements(::Type{Lines}; ...)` to `legend_elements(::Union{Type{Lines}, Type{VLines}, Type{HLines}, Type{ABLines}}; ...)` so that legends from `VLines`, `HLines` and `ABLines` also show the styling.
- Created `legend_elements(::Type{ScatterLines}; ...)` to support `ScatterLines` as well.
Intended to close #435
=> Show styles from mapping in legends from `ScatterLines`, `VLines`, `HLines` and `ABLines`

src/algebra/layer.jl
Since https://github.com/andyferris/Dictionaries.jl/pull/127 has turned into a yak shave about Julia internals, I propose this work around in the meantime.
In the long run, I propose removing `Dictionaries.jl`, since we basically only use it instead of `Dict` for `map(f, ::Dict)`.
=> fix #472 as long Dictioanry.jl isn't fixed

src/paginate.jl
~~I have a plot with many facets that I am not able to `paginate` using the `col` and `row` arguments.~~
`paginate(plt; row, col)` called on a plot that has no `row`/`col` inside `mapping` throws an error.
Fixing this typo prevents the error.
=> Fix a typo leading to `paginate(plt; row, col)` failures

CHANGELOG.md, src/draw.jl, src/guides/legend.jl, test/legend.jl
=> Allow hiding legend or colorbar via `show = false`

CHANGELOG.md, src/algebra/layer.jl, src/algebra/layers.jl, src/algebra/processing.jl, test/algebra.jl
This could be useful, for example, to implement transformations that have multiple layers like mean + std, or something like `gghighlight` where some layers are grayed out and others are left as they are.
=> Add ability to return `ProcessedLayers` from transformations

CHANGELOG.md, Project.toml, src/scales.jl, test/run_reference_tests.jl, test/scales.jl
- **fix natural sorting for tuples**
- **add tests**
- **bump patch version**
- **add changelog entry**
=> Fix natural sorting of tuples

CHANGELOG.md, Project.toml, src/draw.jl, src/paginate.jl, test/paginate.jl
Doing `p = paginate(...); draw(p; axis = (; xlabelcolor = :red))` wasn't working because `axis` is already consumed into `AxisSpecEntries` in the normal pipeline. This PR fixes that by merging `axis` into the existing specs.
=> Axis attributes when drawing pagination

CHANGELOG.md, src/draw.jl, src/paginate.jl, src/scales.jl, test/helpers.jl
Fixes https://github.com/MakieOrg/AlgebraOfGraphics.jl/issues/616
The example from that issue now gives
```julia
julia> draw(..., legend = (position = :bottom))
ERROR: ArgumentError: Can't convert value passed via the keyword `legend` to a
`Dictionary{Symbol,Any}`. If you intended to pass a single-element `NamedTuple`,
check that you didn't write `legend = (key = value)` as this expression resolves to
just `value`. Use either `legend = (; key = value)` or `legend = (key = value,)`.
The invalid value that was passed was:
:bottom
The underlying error message was:
MethodError: no method matching keys(::Symbol)
The function `keys` exists, but no method is defined for this combination of argument types.
Closest candidates are:
keys(!Matched::Base.TermInfo)
@ Base terminfo.jl:232 …
```
=> catch errors in `_kwdict` and give nice error messages

.github/workflows/ci.yml
The `file` option is deprecated in newer `codecov-action`
=> Update codecov options in ci.yml

CHANGELOG.md, Project.toml, src/AlgebraOfGraphics.jl, src/algebra/select.jl, test/algebra.jl, test/runtests.jl
Makes it more convenient to work with table data that has column label metadata attached:
```julia
using AlgebraOfGraphics
using CairoMakie
using DataFrames
using Unitful
df = DataFrame(
t = 1:10,
v = sin.(1:10),
c = sqrt.(1:10) .* u"mg/L",
)
colmetadata!(df, :t, "label", "Time")
colmetadata!(df, :v, "label", "Volume")
colmetadata!(df, :c, "label", "Concentration")
data(df) * mapping(:t, :v, color = :c) * visual(Scatter) |> draw
```
=> Label metadata

docs/src/reference/draw.md, docs/src/tutorials/intro-v.md
Closes https://github.com/MakieOrg/AlgebraOfGraphics.jl/issues/267
Clarifies that the passing of 2D data via `pregrouped` must be seen as experimental, as the rules for this are a bit unclear, yet. Just because it happens to work for some cases does not mean it was intended to or will be supported. I have seen some uses in the wild, though, so an explicit mention seems warranted.
=> Pregrouped matrices docs

CHANGELOG.md, src/algebra/layer.jl, src/algebra/processing.jl, src/algebra/select.jl, src/dict.jl, src/scales.jl, test/algebra.jl, test/runtests.jl, test/utils.jl
This PR makes it more convenient to use the standard forced-categorical mappings `layout`, `row`, `col` and `group` with data whose type AoG doesn't consider categorical. Before, we just errored and said "make your data categorical" but this is a rather redundant step if we know the only correct answer. Of course, users could inadvertently pass a completely wrong column with many different float values which gets them 100 facets now, but there's always ways to shoot yourself in the foot if you're not careful.
It's fairly common to have dataframes with some grouping data in numerical format. Before, you'd get this:
```julia
df = (; x = 1:10, y = 11:20, group = [1, 2, 3, 2, 3, 2, 1, 1, 2, 3])
data(df) * mapping(:x, :y, layout = :group) * visual(Scatter) |> draw
```
```
ERROR: The `layout` …
```
=> Auto categoricals
