- src/AlgebraOfGraphics.jl
- src/algebra.jl
- src/atoms.jl
- src/traces.jl
- test/runtests.jl
With a little care, it is possible to use operations from Julia Base without piracy.
> switch to normal operations

- src/draw.jl
Fixes #50.
``` julia
Pkg.pkg"add https://github.com/JuliaPlots/CairoMakie.jl#pv/update"
using RDatasets: dataset
using AlgebraOfGraphics, AbstractPlotting, CairoMakie
using Underscores, DataFrames
mpg = dataset("ggplot2", "mpg")
mpg[!,:grpx] .= rand.(Ref(["a", "b", "c"]))
mpg[!,:grpy] .= rand.(Ref(["aa", "bb"]))
dta1 = mpg |> data
dta2 = @_ mpg |> 
filter(!((_.grpx == levels(__.grpx)[2]) & (_.grpy == levels(__.grpy)[1])), __) |>
filter(!((_.grpx == levels(__.grpx)[1]) & (_.grpy == levels(__.grpy)[2])), __) |>
data
cols1 = style(:Displ, :Hwy)
grp1 = style(color = :Cyl => categorical, layout_x = :grpx, layout_y = :grpy)
geom = spec(Scatter)
aog1 = dta1 * grp1 * cols1 * geom
aog2 = dta2 * grp1 * cols1 * geom
scn1 = aog1 |> draw # just fine
scn2 = aog2 |> draw # no labels before this PR
``` …
> Faceting: robustify spanned labels

- src/draw.jl
- src/utils.jl
> Labelling code cleanup

- docs/src/generated/internals.jl
- docs/src/generated/tutorial.jl
- examples/gui.jl
- src/AlgebraOfGraphics.jl
- src/analysis/density.jl
- src/analysis/frequency.jl
- src/analysis/histogram.jl
- src/analysis/smooth.jl
- src/context.jl
- src/draw.jl
- src/scales.jl
- src/specs.jl
- test/runtests.jl
> rename spec and style to visual and mapping

- Project.toml
- docs/Project.toml
- docs/make.jl
- docs/src/generated/internals.jl
- docs/src/generated/statistics.jl
- docs/src/generated/tutorial.jl
- src/specs.jl
To make it easier to implement analyses that require all the data.
> minor analysis rework

- src/context.jl
> fix refine_perm

- docs/Project.toml
- docs/src/generated/statistics.jl
Requires https://github.com/JuliaStats/Distributions.jl/pull/1206
> document qqplot

- Project.toml
- src/draw.jl
- src/legend.jl
> Switch to Figure object

- docs/src/generated/tutorial.jl
- src/AlgebraOfGraphics.jl
- src/analysis/frequency.jl
- src/analysis/namedsparsearray.jl
- src/analysis/reducer.jl
- src/draw.jl
Fix #123
Unfortunately, heatmap labels are still a bit "off" due to https://github.com/JuliaPlots/Makie.jl/issues/661
> Refactor reducer and frequency and allow categorical heatmap

- NEWS.md
- src/transformations/histogram.jl
- src/transformations/linear.jl
> rename wts to weights

- docs/src/generated/penguins.jl
- src/algebra/layers.jl
- src/algebra/processing.jl
- src/algebra/select.jl
- src/entries.jl
- src/scales.jl
- src/transformations/density.jl
- src/transformations/frequency.jl
- src/transformations/groupreduce.jl
- src/transformations/histogram.jl
- test/runtests.jl
> group data eagerly

- docs/src/generated/gallery.jl
- src/algebra/layers.jl
- src/algebra/processing.jl
- src/algebra/select.jl
- src/entries.jl
- src/scales.jl
- test/runtests.jl
> Support pre-grouped data

- docs/make.jl
- docs/src/FAQs.md
> add FAQs section to docs

- src/transformations/smooth.jl
I just started using AlgebraOfGraphics a few hours ago and I absolutely love it! This made my day.
Anyway, this PR fixes a small typo.
> Fix typo in docstring

- docs/src/FAQs.md
> Add FAQ entry for combining `Makie` and AoG plots.

- src/AlgebraOfGraphics.jl
- src/guides/colorbar.jl
- src/guides/legend.jl
to make space for improved legend functionality
> Move colorbar stuff to its own file

- docs/gallery/gallery/data manipulations/wide_data.jl
- docs/gallery/gallery/layout/faceting.jl
As defaults changed, these examples are more relevant.
> clarify docs for axis linking

- docs/gallery/gallery/customization/legend.jl
Add example of adjusting legend tile and order or labels
> add adjust legend title and label order

- docs/src/API/functions.md
- src/theme.jl
> Docstrings for `set_aog_theme!` and `aog_theme`

- docs/gallery/gallery/scales/custom_scales.jl
- docs/src/generated/visual.jl
> Clarify documentation of custom scales

- docs/src/generated/analyses.jl
> add examples for free x histogram and density

- docs/gallery/gallery/customization/colorbar.jl
- docs/gallery/gallery/scales/custom_scales.jl
> Extra colormap docs

- docs/gallery/gallery/layout/faceting.jl
Trying to add documentation that faceting must be done with non-numeric variable. I'm editing from GitHub, so apologies if it doesn't render.
> Update faceting.jl documentation that it must be nonnumeric

- docs/gallery/gallery/layout/faceting.jl
Add example for faceting with specified layout to the gallery
> example for faceting with specified layout

- src/transformations/density.jl
- src/transformations/histogram.jl
- src/transformations/linear.jl
> doc improvements

- docs/src/generated/penguins.jl
- src/algebra/layer.jl
- src/scales.jl
> Respect user's colorrange

- docs/src/generated/penguins.jl
https://en.wiktionary.org/wiki/ups#Etymology_2
> small spelling correction

- .github/workflows/CompatHelper.yml
This is now required for CompatHelper to open the PRs
> Update permissions in CompatHelper.yml

- Project.toml
Shouldn't require any code changes I think
> add Dictionaries@0.4 to compat

- Project.toml
- src/algebra/select.jl
- test/algebra.jl
- **fix vector parameterization**
- **add tests**
- **bump patch version**
> Fix `direct` bug

- Project.toml
- src/algebra/layer.jl
- src/algebra/layers.jl
- test/algebra.jl
> Better `Layer` printing

- src/transformations/visual.jl
> Fix link to Makie's docs

- docs/gallery/gallery/customization/colorbar.jl
- docs/src/layers/draw.md
Fixes https://github.com/MakieOrg/AlgebraOfGraphics.jl/issues/530
> Fix colormap example in docs

- CHANGELOG.md
- src/scales.jl
- test/utils.jl
- **Replace `isless` with `natural_lt`**
- **add test**
> Fix `mergesorted` bug

- CHANGELOG.md
- src/guides/legend.jl
- test/legend.jl
- **Apply alpha to legend automatically**
- **test manual override of alpha as well**
- **add changelog**
> Alpha in legend

- CHANGELOG.md
- Project.toml
- **Compute pagination after applying scales (#593)**
- **Bump to 0.9.0**
> Prepare v0.9.0

- CHANGELOG.md
- Project.toml
- src/algebra/select.jl
- test/algebra.jl
- **Fix `mapping` with 4-element pair**
- **add changelog**
- **bump patch version**
> Fix 4-element pair mapping

- docs/src/.vitepress/theme/style.css
- docs/src/index.md
> logo dark mode

- CHANGELOG.md
- Project.toml
- src/scales.jl
- **Fix `from_continuous` use with arbitrary colorscales**
- **changelog and patch bump**
> Fix `from_continuous` with special colormaps

- test/run_reference_tests.jl
CI started to fail after CairoMakie started writing pngs with PNGFiles
> Fix RGB/RGBA image comparison

- docs/src/API/functions.md
- src/algebra/select.jl
Fixes https://github.com/MakieOrg/AlgebraOfGraphics.jl/issues/420
> Add `dims` docstring

- CHANGELOG.md
- src/algebra/processing.jl
- test/algebra.jl
- **make `arr => f` work in plain `mapping`**
- **add test**
> Fix `mapping` with functions
